### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by freeloop4032** [Exo1i/MagiskHluda#1]
模块生效后，server已经启动直接注入App即可？还是，要从新下载同版本server手动启动？

**Comment by Exo1i** [comment]
您好，很抱歉没有在 readme.md 中解释这一点，在 magisk 或 kernelSU 中刷新此模块后，服务器将在第一次重新启动后自动运行。除非有新版本，否则您不需要重新刷新模块。您可以通过在具有 root 权限的终端（我使用 termux）中执行以下操作来验证 hluda-server 是否正在运行：
```su -c netstat -tulpen |grep hluda```
它必须返回以下内容
```
tcp 0 0 127.0.0.1:27042 0.0.0.0:* 监听 0 31449 3064/hluda-server
`````
请注意，hluda-server 默认在端口 27042 上运行

**Comment by freeloop4032** [comment]
模块生效后首次注入没有问题，再次或多次重启后，注入超时，查看端口信息：
OnePlus7T:/ # su -c netstat -tulpen |grep hluda
tcp        0      0 127.0.0.1:27042         0.0.0.0:*               LISTEN      0          69369       5011/hluda-server
tcp        0      0 127.0.0.1:27042         127.0.0.1:43293         ESTABLISHED 0          242203      5011/hluda-server
tcp6       0      0 [::]:40225              [::]:*                  LISTEN      0          108592      5011/hluda-server

麻烦排查下什么原因？

**Comment by Exo1i** [comment]
我确实可以在我自己的设备上确认这一点。 我发现连接超时
![图片](https://github.com/Exo1i/MagiskHluda/assets/121557650/665ea1b8-3a0e-4963-afab-2b6784c92ad6)
但经过一番搜索后，我在 frida 的存储库上发现了这个错误  #https://github.com/frida/frida-core/issues/376。
我做了这些
`1.getprop|grep usap
2. setprop xxxx.usap false
3. pkill usap32
4. pkill usap64
5.重新启动我的设备
`
现在似乎可以正常工作，但如果一段时间后再次出现故障，我会再次回复，
![图片](https://github.com/Exo1i/MagiskHluda/assets/121557650/8bec52f4-50c6-4f80-b36a-825b22456ebf)
您还可以尝试使用 -F 标志附加到最前面的应用程序
