### ISSUE TITLE
占用CPU

### ISSUE THREAD

**Issue by 456vv** [Exo1i/MagiskHluda#3]
hluda-server 空闲时占用CPU 15%左右，个别时候导致手机卡死，黑屏。

**Comment by Exo1i** [comment]
晚上好/早上好。 由于我正忙于期末考试，对于延迟回复表示歉意。 您提到的这个错误似乎与 frida 有关，[此处](https://github.com/frida/frida-core/issues/478#issue-1832948505) 但没有得到官方修复/响应来自开发人员。我帮不了你太多😔！
