### ISSUE TITLE
Device Reboots Randomly

### ISSUE THREAD

**Issue by ptraced** [Exo1i/MagiskHluda#4]
Device Reboots Randomly and crashing

**Comment by Exo1i** [comment]
Hello, sorry to hear this but can you help me by providing some info about your device, also any logs may be helpful (use syslog on play store). This also may be related to this issue [here](https://github.com/Exo1i/MagiskHluda/issues/3#issue-2317692152) try monitoring your CPU usage.I've also found this related [issue](https://github.com/frida/frida/issues/1879) on Frida's repo

**Comment by ptraced** [comment]
> Hello, sorry to hear this but can you help me by providing some info about your device, also any logs may be helpful (use syslog on play store). This also may be related to this issue [here](https://github.com/Exo1i/MagiskHluda/issues/3#issue-2317692152) try monitoring your CPU usage.I've also found this related [issue](https://github.com/frida/frida/issues/1879) on Frida's repo

will log using pixel 5 tho so should be good CPU

**Comment by BrandonSchiller** [comment]
> Hello, sorry to hear this but can you help me by providing some info about your device, also any logs may be helpful (use syslog on play store). This also may be related to this issue [here](https://github.com/Exo1i/MagiskHluda/issues/3#issue-2317692152) try monitoring your CPU usage.I've also found this related [issue](https://github.com/frida/frida/issues/1879) on Frida's repo

only happen on A11 not newer

**Comment by ptraced** [comment]
@Exo1i i updated to A14 Today Seems A11 is effected 🤔 but when i run the Frida manually on A11 i don't reboot so I'm confused

**Comment by Exo1i** [comment]
@TheVisual I'm facing the same issue on miui 14 running android 12 but that's weird as when i had an aosp rom it worked perfectly. I bet that is due to some weird build props or selinux policy. Also the latest build I've just released doesn't cause my device to reboot.

**Comment by Exo1i** [comment]
I promise I'm not here to say that it **works on my device** 😂

**Comment by ptraced** [comment]
> @TheVisual I'm facing the same issue on miui 14 running android 12 but that's weird as when i had an aosp rom it worked perfectly. I bet that is due to some weird build props or selinux policy. Also the latest build I've just released doesn't cause my device to reboot.

will try now thx 🙏

**Comment by Exo1i** [comment]
I've also tried the latest release on lineage os 18.1 which is a11 and runs perfectly

**Comment by ptraced** [comment]
> I've also tried the latest release on lineage os 18.1 which is a11 and runs perfectly

Also btw the florida HREF in read me dosen't redirect to the repo 💯 anyway testing now will keep you updated

**Comment by Exo1i** [comment]
> > I've also tried the latest release on lineage os 18.1 which is a11 and runs perfectly
> 
> Also btw the florida HREF in read me dosen't redirect to the repo 💯 anyway testing now will keep you updated

Thanks for noticing that 😁😅!

**Comment by ptraced** [comment]
> > > I've also tried the latest release on lineage os 18.1 which is a11 and runs perfectly
> > 
> > 
> > Also btw the florida HREF in read me dosen't redirect to the repo 💯 anyway testing now will keep you updated
> 
> Thanks for noticing that 😁😅!

i tried unfortunately still happens but less often now 😢

**Comment by ptraced** [comment]
Upgraded to pixel 8a Dosen't happen anymore and sold my pixel 5 so imma close this
