### ISSUE TITLE
能否适配一下阿尔法面具？

### ISSUE THREAD

**Issue by In1Earth** [Exo1i/MagiskHluda#8]
引用阿尔法面具开发者的话

关于部分本地模块成功安装后实际未刷入的说明

直接安装脚本已于4年前淘汰，在v20.4后应该替换为调用magisk内置安装函数的安装脚本，如果模块开发者坚持不更换脚本使用官方安装流程，那么适配magisk内部行为变化是开发者的责任。
另外，通过命令行安装或者在线更新模块强制执行官方安装流程，仅本地安装需要开发者更新模块安装脚本。

https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh

**Comment by Exo1i** [comment]
你好，我很快就会着手解决这个问题。我会尝试添加更多功能，比如选择特定版本等等，我也会尝试考虑更多功能。

**Comment by Exo1i** [comment]
嘿，刚刚更新了模块并在 magisk alpha 27007 和 kernelsu 上进行了测试 11872。你能确认现在一切正常吗？

**Comment by Exo1i** [comment]
嘿，刚刚更新了模块并在 magisk alpha 27007 和 kernelsu 上进行了测试 11872。你能确认现在一切正常吗？

**Comment by In1Earth** [comment]
我在magisk alpha 27007上正常使用，感谢！

**Comment by Exo1i** [comment]
非常乐意帮忙，干杯！😁
